---
title: "NestJS Request Logger"
date: 2021-05-22
draft: false
---

Je partage ici un retour d'exp√©rience que j'ai fait √† mon travail chez [Koala](https://www.hikoala.co/).

## Les besoins

Je cherche √† avoir un HTTP Logger qui trace les HTTP Requests et les HTTP Responses.

Je veux pouvoir logger aussi bien les requests 404 (aucune route d√©finies) que les requ√™te qui succeed ou m√™me celles qui throw une erreur.

## Comment √ßa marche aujourd'hui

Aujourd'hui on a un `LoggerInterceptor` qui intercepte la requ√™te pour les logger, et attend la r√©ponse pour la logger aussi.

```typescript
@Injectable({ scope: Scope.REQUEST })
export class LoggerInterceptor implements NestInterceptor {
  public constructor(private readonly httpLoggerService: HttpLoggerService) {}

  public intercept(
    context: ExecutionContext,
    next: CallHandler<unknown>,
  ): Observable<unknown> | Promise<Observable<unknown>> {
    const httpContext = context.switchToHttp();
    const { originalUrl: url, method, params, query, body, headers, ip } = httpContext.getRequest<Request>();
    const response = httpContext.getResponse<Response>();

    const obfuscatedHeaders = obfuscateHeaders(headers);

    this.httpLoggerService.logRequest({ url, method, params, query, headers: obfuscatedHeaders, body, ip });

    return next.handle().pipe(
      tap((responseBody) =>
        this.httpLoggerService.logResponse({
          statusCode: response.statusCode,
          headers: response.getHeaders(),
          body: responseBody,
        }),
      ),
    );
  }
}
```

On a un `AnyExceptionFilter` qui intercepte toutes les exceptions qui remonte dans NestJS pour les logger.

```typescript
@Catch()
export class AnyExceptionFilter implements ExceptionFilter {
  public constructor(private readonly moduleRef: ModuleRef) {}

  async catch(exception: unknown, host: ArgumentsHost): Promise<void> {
    const ctx = host.switchToHttp();
    const request = ctx.getRequest();
    const response = ctx.getResponse<Response>();

    const httpException =
      exception instanceof HttpException ? exception : new InternalServerErrorException('Internal Server Error');

    const contextId = ContextIdFactory.create();
    this.moduleRef.registerRequestByContextId(request, contextId);
    const httpLoggerService = await this.moduleRef.resolve(HttpLoggerService, contextId);
    const statusCode = httpException.getStatus();
    httpLoggerService.logResponse({ statusCode, body: exception });

    response.status(statusCode).send(httpException.getResponse());
  }
}
```

## Le probl√®me

Si je fais une requ√™te classique tout va bien:
```JSON
{"requestId":"...d76","type":"REQUEST",...}
{"requestId":"...d76","type":"RESPONSE",...}
```

Si je tape sur une route qui n'existe pas:
```JSON
{"requestId":"...59e","statusCode":404,"body":"NotFoundException [Error]: ...","type":"RESPONSE",...}
```
L√† je n'ai pas la requ√™te.


Et maintenant, si j'ai une erreur qui est thrown dans le controlleur:
```JSON
{"requestId":"...ef4","type":"REQUEST",...}
{"requestId":"...c5d","statusCode":500,"body":"Error: ...","type":"RESPONSE",...}
```

L'id de la request n'est pas la m√™me l'id de la r√©ponse.

## L'explication

Le `LoggerInterceptor` est scopp√© √† une request `@Injectable({ scope: Scope.REQUEST })` or `AnyExceptionFilter` ne l'est pas.

Un composant scopp√© √† une request ne va √™tre instanci√© que lorsque qu'une route est r√©solue. Du coup en cas de 404, le `LoggerInterceptor` n'est pas instanci√© et donc la requ√™te n'est pas logger. J'ai besoin de ce scope, car c'est comme √ßa que je peux d√©finir un id par request (c'est le travail du `RequestContextService`).

`AnyExceptionFilter` a lui aussi besoin du context de la request pour construire un `HttpLoggerService`. Il le r√©cup√®re par un m√©canisme document√© par NestJS: [https://docs.nestjs.com/fundamentals/module-ref#retrieving-instances](https://docs.nestjs.com/fundamentals/module-ref#retrieving-instances)

Le probl√®me c'est qu'au lieu d'essayer de r√©cup√©rer un `HttpLoggerService` existant, on cr√©e syst√©matiquement un nouveau contexte et on demande le `HttpLoggerService` pour ce contexte:

```typescript
const contextId = ContextIdFactory.create();
this.moduleRef.registerRequestByContextId(request, contextId);
const httpLoggerService = await this.moduleRef.resolve(HttpLoggerService, contextId);
```

√áa explique le fait que la request et la response error n'ont sont pas le m√™me id.

## La solution

En creusant un peu dans les internals, j'ai trouv√© que NestJS avait son propre m√©canisme pour identifier des requests. C'est pas document√© et j'ai trouv√© des issues qui en parlent, mais pas d'autre solution que le workaround que j'ai trouv√©.

J'ai fait une PR pour √ßa: [https://github.com/hikoala/monorepo/pull/358](https://github.com/hikoala/monorepo/pull/358)

Concr√®tement je vais r√©cup√©rer le internalId que NestJS set sur l'objet request pour retrouver le `HttpLoggerService` de la request:

```typescript
let contextId = request[REQUEST_CONTEXT_ID];
const contextIdWasNotDefined = contextId === undefined;

if (contextIdWasNotDefined) {
  contextId = ContextIdFactory.create();
  request[REQUEST_CONTEXT_ID] = contextId;
  this.moduleRef.registerRequestByContextId(request, contextId);
}

const httpLoggerService = await this.moduleRef.resolve(HttpLoggerService, contextId);
```

Si le internalId n'est pas set, c'est que le context n'a pas √©t√© cr√©√© par NestJS (404). Je cr√©e donc un internalId que je set sur la request et j'enregistre la request avec cet id dans NestJS.

C'est pas id√©al,  je pr√©f√®rerais pass√© par des helpers fournis par NestJS pour trouver l'id d'un context √† partir d'une request. Mais √ßa n'existe visiblement pas. Donc en attendant... üòÖ
